create table if not exists games (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  genre text default '',
  version text default '1.0.0',
  size text default '',
  description text default '',
  cover_url text default '',
  logo_url text default '',
  trailer_url text default '',
  game_file_url text default '',
  game_file_name text default '',
  created_at timestamptz default now()
);

create table if not exists game_images (
  id bigint generated by default as identity primary key,
  game_id uuid references games(id) on delete cascade,
  image_url text not null,
  created_at timestamptz default now()
);

alter table games enable row level security;
alter table game_images enable row level security;

create policy "public can read games" on games for select using (true);
create policy "public can read images" on game_images for select using (true);

-- Storage bucket:
-- In Supabase Dashboard > Storage create a PUBLIC bucket named: games
